env:
  browser: true
  es6: true
  jquery: true
  node: true
extends: 'eslint:recommended'
globals:
  Chart: false
  Cookies: false
  dragula: false
  later: false
  M: false
  moment: false
  Prism: false
parserOptions:
  sourceType: module
rules:
  indent:
     - error
     - 4
     - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  no-console: 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
