name: Docker

on:
  pull_request:
  push:
  release:
    types: [published]

env:
  IMAGE_ID: ${{ github.repository }}

jobs:
  docker:
    name: Docker
    uses: dargmuesli/github-actions/.github/workflows/docker.yml@0.1.0
    with:
      IMAGE_ID: ${{ github.repository }}
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
