name: Docker

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    name: Build
    uses: dargmuesli/github-actions/.github/workflows/docker.yml@0.23.3
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
  deploy:
    if: github.event_name != 'pull_request'
    name: Deploy
    needs: build
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [19]
    steps:
    - name: Checkout git repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

    - name: Setup package manager
      run: corepack enable

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: ${{ inputs.PACKAGE_MANAGER }}
        cache-dependency-path: ${{ inputs.CACHE_PATH }}
        node-version: ${{ matrix.node }}

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/pnpm-lock.yaml')) }} # TODO: make independent from package manager (https://github.com/dargmuesli/github-actions/issues/7)

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pnpm install # TODO: make independent from package manager (https://github.com/dargmuesli/github-actions/issues/7)

    - name: Build
      run: pnpm run generate

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: f00135e2a8cc575a4bc4817c9521fe71
        projectName: jonas-thelemann
        directory: dist
        gitHubToken: ${{ secrets.GH_TOKEN }}
  release-semantic:
    needs: build
    name: Release (semantic)
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@0.23.3
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
  release-assets:
    needs: release-semantic
    name: Release (assets)
    uses: dargmuesli/github-actions/.github/workflows/release-assets.yml@0.23.3
