name: Docker

on:
  pull_request:
  push:

jobs:
  build:
    name: Build
    uses: dargmuesli/github-actions/.github/workflows/docker3.yml@0.25.8
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
    with:
      ARTIFACT_PATH: .output/public
  release-semantic:
    needs: build
    name: Release (semantic)
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@0.25.8
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    name: Deploy
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: f00135e2a8cc575a4bc4817c9521fe71
        projectName: jonas-thelemann
        directory: .
        gitHubToken: ${{ secrets.GITHUB_TOKEN }} # set this to enable GitHub deployments
